### ISSUE TITLE
User configuration and document storage schema

### ISSUE THREAD

**Issue by MATEOMC** [Wilab-io/sample-apps#3]
## Problem to solve

**As a** system architect
**I want** to design a robust database schema
**So that** we can store user-specific configurations, documents, and system settings

## Tasks

-   [x] #19 

## Acceptance criteria

-   [ ] User Profile and Configuration Storage
    **Given** a new user is registered in the system
    **When** the user profile is created
    **Then** the database should create the following entities:

-   [ ] Document Indexing and Storage Validation
    **Given** a PDF or image document is uploaded
    **When** the document is processed
    **Then** the system should:
      * Generate a unique document_id
      * Store document metadata in Document_Metadata table
      * Associate the document with the uploading user's user_id
      * Create an indexed reference for full-text search

 -   [ ] Vespa.AI Configuration Management
    **Given** a user modifies Vespa.AI configurations
    **When** configuration changes are submitted
    **Then** the system should:
      * Update the Vespa_Configuration table
      * Log configuration change history 
      * Validate configuration syntax before storage
      * Ensure configuration is user-specific
      * Display changes in front	

 -   [ ] Demo Questions Management
    **Given** a user modifies Demo_Questions configurations
    **When** configuration changes are submitted
    **Then** the system should:
      * Update the Demo_ Questions table
      * Log configuration change history
      * Validate configuration syntax before storage
      * Ensure configuration is user-specific
      * Display changes in front.

## Proposed diagram

```mermaid
%%{
  init: {
    'theme':'base',
    'themeVariables': {
      'primaryBorderColor': '#000000'
    }
  }
}%%

erDiagram
    USER {
        string userID PK
        string username
        string passwordHash
    }
    USER_DOCUMENT {
        string documentID PK
        string userID FK
        string documentName
        timestamp uploadTS
    }
    USER_SETTINGS {
        string userID PK
        string[] demoQuestions
        string ranker
        string vespaHost
        int vespaPort
        string vespaToken
        string geminiToken
        string vespaCloudEndpoint
        string schema
        string prompt
    }
    
    USER ||--o{ USER_DOCUMENT : "has"
    USER ||--|| USER_SETTINGS : "has"
```
